# Generated by Django 5.0.7 on 2024-07-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Купоны', 'verbose_name_plural': 'Купоны'},
        ),
    ]
